Tyler-IN/MnB2-Bannerlord-CommunityPatch

src/CommunityPatch/Patches/StewardReevePatch.cs
src/CommunityPatch/Patches/StewardRulerPatch.cs

Fixes #20 Reeve perk
Fixes #41 Ruler perk

Steward perk patches

---

src/CommunityPatch/CommunityPatchSubModule.cs
src/CommunityPatch/PatchBase.cs
src/CommunityPatch/Patches/HealthyScoutPatch.cs
src/CommunityPatch/Patches/PeakFormPatch.cs

Fixes https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/30

Fix Healthy Scout & Peak Form perks, implementation via Harmony patching

---

src/CommunityPatch/Patches/StewardProminencePatch.cs
src/CommunityPatch/Patches/StewardSupremeAuthorityPatch.cs

Fix Prominence and Supreme Authority perks

---

src/CommunityPatch/Patches/WarRationsPerkPatch.cs

Carrying on where @Skau left off tonight;
Fixes #36.

War Rations fix

---

src/CommunityPatch/Patches/AgriculturePerkPatch.cs

Fix for Agriculture

---

src/CommunityPatch/Patches/AgriculturePerkPatch.cs

https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/75

Replay PR #75

---

README.md
src/CommunityPatch/Patches/PrisonerRecruitmentPatch.cs

Fixed off-by-one error in default prisoner recruitment model

---

README.md
src/CommunityPatch/Patches/StewardAssessor.cs

Fix for Assessor perk

---

README.md
src/CommunityPatch/Patches/StewardNourishSettlement.cs

Fixes #31 
(This is actually Skau's PR)

Fix for Nourish Settlement

---

README.md
src/CommunityPatch/Patches/StewardTaxCollector.cs

Fix for Tax Collector

---

README.md
src/CommunityPatch/Patches/WarmongerPatch.cs

Fix for #32.
This one is also ambiguous in the description, but is initialized with a -0.35 primary bonus. I interpreted that to be a decrease in cost by 35%.

Warmonger fix

---

README.md
src/CommunityPatch/Patches/LogisticsExpertPatch.cs

Fixes issue #34 
Even though the text doesn't mention the increase in speed, the perk is initialized with a en effect of 0.1, so I just went with that. We can add an option for it if it's wanted.

Fixed Logistics Expert

---

README.md
src/CommunityPatch/Patches/NeutralClanTierUpPatch.cs

#105: Fix for neutral clans tiering up causing CTD

---

README.md
src/CommunityPatch/Patches/ProsperousReignPatch.cs

Prosperous Reign patch

---

README.md
src/CommunityPatch/Patches/Perks/Intelligence/Steward/FoodRationingPatch.cs

Fixed Food Rationing Perk

---

README.md
src/CommunityPatch/Patches/Perks/Endurance/Riding/SquiresPatch.cs

Fixed squires perk

---

README.md
src/CommunityPatch/Patches/Perks/Endurance/Riding/ConroiPatch.cs

Fixed Conroi perk

---

src/CommunityPatch/Patches/Perks/Endurance/Riding/ConroiPatch.cs
src/CommunityPatch/Patches/Perks/Endurance/Riding/SquiresPatch.cs
src/CommunityPatch/Patches/Perks/Intelligence/Steward/Assessor.cs
src/CommunityPatch/Patches/Perks/Intelligence/Steward/BannerlordPerkPatch.cs
src/CommunityPatch/Patches/Perks/Intelligence/Steward/ManAtArmsPatch.cs
src/CommunityPatch/Patches/Perks/Intelligence/Steward/StewardSwordsAsTributePerkPatch.cs

Base removed + fixed Bannerlord and ManAtArms

---

README.md
src/CommunityPatch/Patches/Perks/Endurance/Riding/FilledToBrimPatch.cs

Fixed Filled To Brim

---

README.md
src/CommunityPatch/FloatHelper.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/EverydayEngineerPatch.cs

https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/199

Replay #199

---

README.md
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/BuilderPatch.cs

This perk increases building speed. I check whether the town has a governor with the perk active, then I increase its production power by 50%.

add perk Builder from engineering tree

---

README.md
src/CommunityPatch/Patches/Feats/AgilityPatch.Shared.cs
src/CommunityPatch/Patches/Feats/BattanianForestAgilityPatch.cs
src/CommunityPatch/Patches/Feats/KhuzaitCavalryAgilityPatch.cs
src/CommunityPatch/Patches/Feats/SturgianSnowAgilityPatch.cs

Merging functionality from Cultural Feat Fixes
https://github.com/wonkotron/CulturalFeatFixes
- Battanian Forest Agility
- Khuzait Cavalry Agility
- Sturgian Snow Agility
- Snow movement debuff based on atmospheric data at party location

Add patches to fix movement bonuses and the snow debuff

---

README.md
src/CommunityPatch/CommunityPatchSubModule.Options.cs
src/CommunityPatch/Patches/MenuWhenEncountingAnArmyPatch.cs

Implementation of https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/120#issuecomment-613501060
A menu will pop up when encoutering a **neutral** army enabling the player to : 
* talk to the army's leader
* talk to the other members
* leave
A menu will pop up when encoutering an **enemy** army enabling the player to : 
* talk to the army's leader
* attack
* leave

Menu when encountering an army

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Roguery/EscapeArtistPatch.cs

Add perk escapist artist from roguery tree. The perk makes player escape captivity 30% faster. This feature is player only.

add escapist artist roguery perk

---

README.md
src/CommunityPatch/Patches/Feats/AgilityPatch.Shared.cs
src/CommunityPatch/Patches/Feats/BattanianForestAgilityPatch.cs
src/CommunityPatch/Patches/Feats/DisableTaleWorldsAgilityBonusesPatch.cs
src/CommunityPatch/Patches/Feats/KhuzaitCavalryAgilityPatch.cs
src/CommunityPatch/Patches/Feats/SturgianSnowAgilityPatch.cs

Fix agility feat patches for e1.3.0.226834

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Roguery/BribeMasterPatch.cs
src/CommunityPatch/Patches/Perks/Cunning/Roguery/NegotiatorPatch.cs

This PR adds two perks that reduces bribe prices by 50% each. However, I made they stack multiplicatively so there will always be a price for a bribe.

add perk Negotiator and Bribe master from roguery

---

README.md
src/CommunityPatch/Patches/Perks/Endurance/Riding/HorseGroomingPatch.cs

Implementation for the Horse Grooming perk. (#154)

Horse Grooming perk

---

src/CommunityPatch/Patches/EarlyStoryVisibleTimeoutPatch.cs

format story patch: use short method syntax

---

src/CommunityPatch/Patches/Perks/Intelligence/Steward/RulerPatch.cs

A mid release update for 1.4 beta on 2020-05-11 removed the Town.All property so use Campaign.AllTowns instead.
This assumes that AllTowns represents specifically towns as opposed to towns OR castles. Probably true since there is also an AllCastles property.

Adjust to changes in Bannerlord's Town api

---

src/CommunityPatch/Patches/Perks/Intelligence/Steward/RulerPatch.cs

BuildInvoker instead of calling Invoke directly

cleanup ruler patch

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Roguery/ConcealedBladePatch.cs

Add concealed blade perk

---

README.md
src/CommunityPatch/Patches/Perks/Control/Throwing/ConcealedCarryPatch.cs

Add concealed carry perk
