README.md
src/CommunityPatch/Patches/BannerlordPerkExplainerPatch.cs
src/CommunityPatch/Patches/BannerlordPerkPatch.cs

This is a fix for #33 
I split it into two patches - one for the actual party size limit logic and one for the tooltip when you hover over the party size as shown here:
I postfix PartyBase.get_PartySizeLimit and PartyBase.get_PartySizeLimitExplainer respectively.
In BannerlordPerkExplainerPatch I reuse the method from BannerlordPerkPatch to make it consisent.
Once again we're in the situation on how we want to interpret TaleWorlds wording: 
*+2 party size for each fief that you own*
I opted to go for the approach where the party leader is chosen as the check if the perk is available. Then it uses the party leader current clan and gets all its settlements. This means that any companion or NPC will get benefits of Bannerlord (if they can get the perk at all?). 
All settlements means that …

Bannerlord perk

---

README.md
src/CommunityPatch/Patches/ManAtArmsExplainerPatch.cs
src/CommunityPatch/Patches/ManAtArmsPatch.cs

Fix for #39.
Interpreted the same as #56 because the wording is exactly the same.
They stack appropriately.

Fixed Man-At-Arms

---

README.md
src/CommunityPatch/Patches/StewardSwordsAsTributeExplainerPatch.cs
src/CommunityPatch/Patches/StewardSwordsAsTributePerkPatch.cs

Fix for #38 
*+10 party size for every vassal*
It properly stacks with the other party size patches.
It checks if the party leader's clan is the ruling clan of the kingdom and gets the count of all clans, excluding itself. Does that make sense? I think that is the vassals. Aka other clans in a kingdom.

Steward Swords As Tribute fix

---

README.md
src/CommunityPatch/CommunityPatch.csproj
src/CommunityPatch/Patches/LearningRateExplainerPatch.cs

The learning rate calculator was accidentally passing it's explainer to the learning limit calculator.
Fixes #68

Fix Learning Rate explanation

---

src/CommunityPatch/Patches/PrisonerRecruitmentPatch.cs

Official patch would likely change the actual daily tick event to modify the way they check tiers or some other way in that method, not this 'hackier' fix, so lets check IL of the DailyTick as well.

Made prisoner recruitment code more robust to official patches

---

src/CommunityPatch/Patches/LearningRateExplainerPatch.cs

Since this is fixing CalculateLearningRate, not CalculateLearningLimit; there's nothing wrong with it and I'm not changing it's behavior, I need to be checking the hash of CalculateLearningRate instead.
The patches still apply to CalculateLearningLimit

Learning Rate explanation patch IsApplicable check fix

---

README.md
src/CommunityPatch/Patches/StewardEnhancedMinesPatch.cs

Fixes #37 
Applies to all villages that have a primary production that isn't food because that seems to be the check used for increasing production for the tradeyard foreman perk

Fix for enhanced mines perk

---

src/CommunityPatch/Patches/StewardSwordsAsTributePerkPatch.cs

Tested it and looks good now. Fixed because a comment on nexusmods mentioned that it applied even when the player was just a vassal.

Fixed Swords and Tribute to only be applied to rulers

---

README.md
src/CommunityPatch/Patches/Perks/Intelligence/Steward/ReconstructionPatch.cs

Fix for #46 
The amount was ambigious. Neither the description or the perk initialization had a value. The default value passed in for healing is hardcoded in `VillageHealCampaignBehavior.DailyTick` (0.06), so I ended up multiplying this by 2. 
The value could probably be bigger though, this is a 275 skill perk.
I am currently on e1.0.10, so that's the only hash, if anyone is on the beta branch and wants to quickly check if the hash is different, please do.

Reconstruction Perk Fix

---

src/CommunityPatch/Patches/Policies/LandGrantsForVeteransPatch.cs

Typo causing a wrong hash check :

fix land grants for veteran patch hash check

---

README.md
src/CommunityPatch/CommunityPatch.csproj
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/BallisticsPatch.cs

I have patched two different methods: SandBoxUIHelper.GetSiegeEngineTooltip and SiegeEvent.BombardHitEngine. 
The first is responsible for creating the siege units tooltips. I added a new tooltip property saying when the Ballistic perk is active. It only shows up when some leader from the defender team have the perk activated, and player is previewing the Catapult. It takes into consideration that catapults are only placeable in the defensor team. 
The latter method is the one that actually applies the damage. Before applying the damage, I make a calculation to first apply a bonus damage. This extra damage only occurs when the conditions are match: some leader hero from the catapult team must have the Ballistic Perk activated.

add implementation for Ballistics perk from Engineering tree

---

README.md
src/CommunityPatch/CommunityPatch.csproj
src/CommunityPatch/CommunityPatchSubModule.cs
src/CommunityPatch/Patches/EarlyStoryVisibleTimeoutPatch.cs

Fixes #133 . Now those quests will appear with the days until failure much like other quests.
Unfortunately there's a few hours game time ( 10 seconds or so real life time) until the quests are updated after getting them. See code [comments](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/150/commits/0cc24f958e1d111d549891ffe08af49e0f40ae94#diff-4cb347780d4b8f8827fabdb6f694148dR105).

Fix user not being told that FirstPhase story quests fail in 10 years

---

src/CommunityPatch/Patches/Perks/Intelligence/Engineering/BallisticsPatch.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/HeavierSiegeEnginesPatch.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/SiegeTooltipHelper.cs

This pull request adds a new perk to the game called 'Heavier siege engines', which should add 20% of bombardment damage against other siege engines. In order to do this, it was necessary to patch the 'SiegeEvent.BombardHitEngine', where the damage is applied to siege engine constructions. 
Besides the damage, it was also necessary to patch 'SandBox.ViewModelCollection.SandBoxUIHelper.GetSiegeEngineInProgressTooltip' to correctly display the perk buff and a tooltip updated with new damage values. Since there is a bunch of logic behind it, and same logic will repeat for at least three other perks, a new Helper class was created.
The SiegeTooltipHelper contains useful methods to deal with tooltip update, and also for easy patching the mentioned 'GetSiegeEngineInProgressTooltip'. 
There is …

add perk 'heavier siege engines' from engineering tree and helper to organize and reuse code for next perks 

---

README.md
src/CommunityPatch/FloatHelper.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/GoodMaterialsPatch.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/SiegeEngineConstructionExtraDataManager.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/SiegeTooltipHelper.cs

This pull request adds the perk 'Good Materials', which increases your siege engines max health by 20%.
There are two commits to add the perk 'Good Materials' from engineering tree. The first one only deals with the damage application without any visual tooltips. The second one is supposed to implement the visuals, displaying the increased Max Health Points, which were very tricky to do due to lifecycle limitations when patching. 
**Commit 1**
The first commit have three patches. Since there are two routes to deploy a siege engine, one for player and another for AI, I had to patch them both. However, the player route required two patches to avoid adding references from 'SandBox.ViewModelCollection' into the project.
These two patches check whether the 'deployed siege engine list' has …

Good materials perk from engineering tree

---

README.md
src/CommunityPatch/FloatHelper.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/EverydayEngineerPatch.cs

Add the perk 'everyday engineer' which should improve all default town projects by 60%. 
There is a method that is called to get the effect power of every project. I patched this method, checking if its type is 'DefaultProject' before applying the perk bonus. 
Since all default town projects have an effect power of 1, and the value type is integer, the perk is actually doubling the effect power instead of increasing by 60%.

add perk everyday engineer from engineering three

---

Directory.Build.props
README.md
src/CommunityPatch/CommunityPatch.csproj
src/CommunityPatch/Properties/launchSettings.json
tools/Antijank/Antijank.csproj
tools/GeneratePatchTargetHashes/GeneratePatchTargetHashes.csproj
tools/UnblockFile/UnblockFile.csproj

Updates the readme to tell people the intended place for the repo. (the Modules dir).
Also reduce repetition in \*.csproj files by moving reference etc paths to project properties like 'MnB2BannerlordBinDir' when possible. While it works without this, someday someone might want to build with Bannerlord or the repo somewhere else and this would help them.

Make project easier to build for new people

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Roguery/EyeForLootPatch.cs
src/CommunityPatch/Patches/Perks/Cunning/Roguery/RaidingHelper.cs
src/CommunityPatch/Patches/Perks/Cunning/Roguery/RaidingPartyPatch.cs
src/CommunityPatch/Patches/Perks/Vigor/TwoHanded/QuickPlunderPatch.cs

This pull request adds three perks that are all related and very similar in the implementation. Due to the very similarity in code, I thought it made sense to PR it all together. These are the affected perks related to raiding: 
- Quick plunderer (two handed tree): +5% raiding speed
- Raiding party (roguery): +10% raiding speed
- Eye for loot (roguery): +5% raiding loot
**Raiding System**
It is worth explaining how the raiding system works. When a character is raiding a settlement, it shows up a raiding bar that is just the settlement HP. Everytime the raiding damage is applied, loot are given to the player. However, it is worthy noting that the damage is only applied in amounts equal or bigger than 5% of the settlement hp (settlement HP is a factor from 0 to 1). So any lesser damage is …

Add perks related to raiding

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Roguery/ForTheThrillPatch.cs

The perk for thrill is supposed to increase morale gain on raids by 10%. However there is no morale gain during or after a raid. So, to make this perk any useful without deviating from its description, I have implemented a small morale reward from raids. When a party/parties finishes a raid, they all receive 4 morale points in 'Recent Events'.

add morale gain on raiding and the perk for the thrill from roguery

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Roguery/SlipIntoShadows.cs
src/CommunityPatch/Patches/Perks/Cunning/Roguery/SlipIntoShadowsPatch.cs

Add the scout perk 'Slip into shadows' which reduces the chances of being caught when sneaking into towns by 20%. It seems the sneaking is a player only functionality.

add perk slip into shadows from roguery

---

README.md
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/ArmorcraftPatch.cs

I added the Armorcraft perk that increases character's armor by 10%. I had just to postfix the Agent.GetBaseArmorEffectivenessForBodyPart, to increase its output by 10% when the Agent had the perk active.

add perk Armorcraft from Engineering tree

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Roguery/MerryMenPatch.cs

This PR adds the roguery perk  Merry men' that should allow you to recruit bandits. Recruiting bandits was already possible but would required a massive army to intimidate them. Not just that, it would require also luck. By having the perk, the recruitment should require just a minimum number of soldiers and nothing else. 
An important note. The perk ID was not unique, it was the same as the bow perk 'Merry Men'.

add the roguery perk Merry men

---

README.md

Adds the roguery perk 'Slave trader' which increases your profits from ransoming by 20%. It seems every ransom related action calls the method CharacterObject.PrisonerRansomValue to determine the value of the prisioner; even when bartering them.

add perk slave trader from roguery

---

README.md
src/CommunityPatch/FloatHelper.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/ImperialFirePatch.cs

This pull request will add the perk 'Imperial Fire' which should enable fire siege engines. These fire engines were already enabled by default to every player. So what I had to do is removing those options from players that didn't have the perk active. 
There were two methods to be patched, one for the attacker team, the other for the defender team.

add Imperial Fire Perk from Engineering tree

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Tactics/TacticalSuperiorityPatch.cs

This adds the perk tactical superiority which increases soldiers damage by 5% during simulations. There is a method that calculates the soldiers damage. I just had to postfix it and increase the output by 5% when striker party leader had the perk active.

add perk tactical superiority from tactics

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Tactics/CompanionCavalryPatch.cs

This PR adds the perk Companion Cavalry which increases cavalry morale damage by 10%, if leader has the perk active.
Morale loss is applied when a soldier dies in combat, applying a AOE morale damage to nearby friends. So the implementation checks if the killer has a mount and a leader with the perk active, then the it applies a second AOE morale damage, but just with the bonus amount (10%).

add Companion Cavalry perk from tactics tree

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Roguery/BriberPatch.cs

This pull request adds the perk Briber from roguery. It increases the chances of bribery dialogues to appear by 15%. When you try to force a villager or caravan into giving you their money, it opens bribery related dialogues in case of success. The chances are defined like this: When your party is stronger than the villager/caravan in a certain proportion, you get 66% chance of success; otherwise you receive only 33%. So the perk increases this chance, opening bribery dialogues on success.

add perk Briber from roguery

---

README.md
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/BallisticsPatch.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/SiegeTooltipHelper.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/WallBreakerPatch.cs

Add the 'wall breaker' perk that increases damage to walls by 25%. Since from now on the damage to walls differ from the damage to siege engines, I have added a new tooltip property so the player can clearly see how much damage he can apply to each target.

add perk wall breaker and tooltip for ranged wall damage

---

README.md
src/CommunityPatch/FloatHelper.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/ResolutePatch.cs

Adds the 'resolute' perk which is supposed to reduce morale loss during sieges. 
This patch grabs every negative effect on morale and reduce their impact by a rate. The rate is calculated based on the party members that have the perk activated. The bonus is 50%, however, they are not additive, meaning they stack multiplicatively. 
So if the player is having a -30 morale debuff because of starvation, one member having this perk would reduce the effect to -15 (50%). Two members would reduce by 75% instead.
The morale loss reduction effects apply only when the perk is active and the character party is on siege.

add the Resolute perk from engineering tree

---

src/CommunityPatch/Patches/EarlyStoryVisibleTimeoutPatch.cs

Instead of the patch stopping if we are in multiplayer, instead stop if we are in any game mode other than CampaignStoryMode.
I'm not absolutely certain, but basically because all the base game code checks in the this way (for CampaignStoryMode) before accessing story mode vars. Also hypothetically TW might add a new game mode in the future which is not multiplayer but is also not CampaignStoryMode and in that case the patch would incorrectly apply itself.

EarlyStoryVisibleTimeoutPatch: check for game type being story mode

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Tactics/OneStepAheadPatch.cs

This PR adds the perk 'one step ahead' from tactics tree that says 'Allows you to place your troops before all battles'. 
What I have implemented is the enabling of the 'Party [P]' menu when an Battle event is about to happen and perk is active. So you can organize your party formation before battle. This likely might not be the real expectation for the skill, but I thought it could be a good temporary replacement while TW don't implement the perk.

add 'one step ahead perk' from tactics

---

src/CommunityPatch/Patches/EarlyStoryVisibleTimeoutPatch.cs

* Hide quest remaining days if it never expires
* else we get very ugly text on the screen "-2147483648 days left" as quests never expiring were obviously not meant to have that displayed. This happens briefly between OnQuestStarted and the next hourly tick. Also can happen if another mod or part of the game changes the quest to never timeout.
* Explicitly show timeout on two quests that are part of FirstPhase but not in the associated namespace
* MeetWithArzagosQuest and SupportKingdomQuest. They're not in the StoryMode.Behaviors.Quests.FirstPhase namespace but are actually part of the first phase.
* Ensure HourlyTick handlers don't remove each other
* by registering them each with a seperate owner, as opposed to having them all be owned by the patch class. Previously each would remove …

Fix story patch UI oddities, add missing first phase quests, misc fixes

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Tactics/AmbushSpecialistPatch.cs
src/CommunityPatch/Patches/Perks/Cunning/Tactics/HammerAndAnvilPatch.cs
src/CommunityPatch/Patches/Perks/Cunning/Tactics/PhalanxPatch.cs
src/CommunityPatch/Patches/Perks/Cunning/Tactics/SimulateHitPatch.cs
src/CommunityPatch/Patches/Perks/Cunning/Tactics/TacticalSuperiorityPatch.cs

This PR adds three new simulation damage perks and refactor the existent one to make use of a base class. The base class is named SimulationHitPatch, and it has all the four patches basic implementation to avoid code repetition. 
The perks added are:
- Phalanx: "Your infantrymen deal 50% more damage to cavalry in simulations."
- Hammer and Anvil: "Your cavalry deal 50% more damage to archers in simulations"
- Ambush Specialist:  "Archers deliver 60% more damage in simulation in forests"
The one refactored is:
- Tactical Superiority: "Your soldiers deal %5 more damage in simulations"

add simulation damage perks

---

README.md
src/CommunityPatch/Patches/ExtraAmmoPerksPatch.cs
src/CommunityPatch/Patches/Perks/Cunning/Tactics/LogisticsPatch.cs

Add perk logistics from Tactics tree. It should increase troops ammo by 20%. 
I have created a class that inherits from ExtraAmmoPerksPatch. However, since the buff is to the troops, not to the hero, I had to refactor ExtraAmmoPerksPatch to allow it. There is a new method to apply the perk to an Agent instead of Hero. 
I have made sure the other perks that increases ammo are still working.

add perk Logistics from tactics

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Tactics/BaitPatch.cs
src/CommunityPatch/Patches/Perks/Cunning/Tactics/PlayerEncounterHelper.cs

This PR adds the perk bait, which should increase reinforcement range by 30% (party member).
In order to do so, I have patched the method responsible for bringing the nearby troops (both ally and enemy) into battle. Since the range values were hardcoded in a very big method, I had the idea to make a postfix that would search for nearby parties a second time, but this time with the range increased.
The down side is that the scan is done twice, however, since this is just a player feature that triggers only when his/her battle is going to start, it shouldn't be a performance problem.

add the perk Bait from tactics

---

src/CommunityPatch/CommunityPatch.csproj

This fixes #261.
@iPherian _how on earth did you narrow it down? :smile:_ 
Anyway, if IntelliSense for some reason doesn't like `SourceRevisionId` property, a `$(DesignTimeBuild)` condition should fix it without breaking the "real" builds.

fix IntelliSense completion

---

README.md
src/CommunityPatch/Patches/Perks/Cunning/Tactics/TrustedCommandersPatch.cs

Adds the perk 'Trusted Commander', which reduces the cohesion cost of armies by 50%. The description doesn't mention the value, I just kept the one already specified in the DefaultPerks class. Since this is a party member bonus, I made it stack multiplicatively.

add perk Trusted Commanders from tactics

---

src/CommunityPatch/Patches/Perks/Endurance/Riding/TramplerPatch.cs
src/CommunityPatch/Patches/Perks/Endurance/Riding/TramplerPatch2.cs

Taleworlds added in the 1.4.0 beta patch the ```AttackInformation``` class in order to have clearer method signatures.
This change impacts the  ```GetAttackCollisionResults``` method with a new ```AttackInformation``` parameter holding most of the previous attack parameters (method signature before 1.4.0) especially the attacker character object.
This one is needed to check if the rider's character has got the trampler perk or not.
Moreover, the ```TramplerPatch2``` will not be loaded in patches prior to 1.4.0 since the compiler does not know what  the ```AttackInformation``` class is.

Trampler perk implementation for 1.4.0 beta

---

src/CommunityPatch/Patches/Perks/Social/Leadership/UltimateLeaderPatch.cs

fixes Tyler-IN/MnB2-Bannerlord-CommunityPatch#275
- Base game has duplicate perks, apply when either are active
- Remove requirement of being head of faction or independent

patch perk Ultimate Leader

---

README.md
src/CommunityPatch/Patches/Feats/AseraiCheapCaravansPatch.cs

This perk is fixed for player characters, and presumed fixed for AI as of e1.3.0

Disable AseraiCheapCaravans for e1.3.0+

---

src/CommunityPatch/Patches/EquipDraggedNonCivilianItemPatch.cs

#284 
Non civilian items can be equipped when in civilian mode in the inventory screen.
When switching characters, or transferring items from both left and right inventories or resetting the transactions, the player should be able to equip the displayed character with the items described by the perk.
Multiple patches can be added to allow more items to be available in civilian mode if the displayed character has all perks.
If multiple patches describe the same items, there could be some collision issues. But this shouldn't occur anytime soon with the way perks are thought out.
This should be compatible with :
- **e1.3.1**.228624
- **e1.4.0**.229335
- Beta **e1.4.1**.229326

Add base for Concealed Perks

---

src/CommunityPatch/CommunityPatchSubModule.Options.cs

Window closes with no effect if "Apply" is clicked with no option selected.
Just an empty check before entering the switch.  Solves #337

Fix crash when applying no option.

---

src/CommunityPatch/Patches/Perks/Control/Bow/BattleEquippedPatch.cs

Somehow BattleEquippedPatch was referring to BowMountedArcher perk.

use correct perk in Bow.BattleEquippedPatch

---

README.md
src/CommunityPatch/Patches/Perks/Endurance/Smithing/LegendarySmithUiPatch.cs

Fix either Legendary Smith or Siege Expert not being selectable by the player.
This is a UI only fix and doesn't implement the Siege Expert perk.

Fix UI for Tier 11 Smithing perks

---

src/CommunityPatch/CommunityPatchSubModule.Patching.cs
src/CommunityPatch/PatchApplicabilityHelper.cs
src/CommunityPatch/Patches/Perks/Intelligence/Engineering/BuilderPatch2.cs
src/CommunityPatch/Patches/Perks/Social/Leadership/DisciplinarianPatch.cs

BuilderPatch and BuilderPatch2 patches were wrongly applied. BuilderPatch is obsolete since e1.3.0 and was still applied after 1.3.0+.
- Skip patches that have the PatchObsolete / PatchNotBefore attribute and being not applicable to current game version.
- Makes skipped patches clearer with the addition of "Obsolete" or "Non compatible" patch messages instead of "Skipped".

Skip patches when PatchObsolete/PatchNotBefore is used

---

src/CommunityPatch/Patches/PerkPatchBase.cs
src/CommunityPatch/Patches/Perks/Cunning/Roguery/MerryMenPatch.cs
src/CommunityPatch/PerkObjectHelpers.cs

Currently Roguery.MerryMenPatch is referring to BowMerryMen perk, because it has the same name as RogueryMerryMen perk.
This RogueryMerryMen is indeed rogue as it doesn't even have a property in DefaultPerks so had to find it by StringId.
The workaround is quite ugly but I could not find any better way, maybe you can help with this?
Btw TW has also BowMountedArcher and RidingMountedArcher with the same problem.

use correct perk in Roguery.MerryMenPatch
